M48
; DRILL file {KiCad 7.0.9} date Mon May 20 07:51:08 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-20T07:51:08-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X0.921Y-1.3167
X0.926Y-6.1621
X6.91Y-6.1601
X6.911Y-1.3177
T2
X6.22Y-4.1146
X6.67Y-4.1146
T0
M30
